#!/usr/bin/php
<?php
/*------------------------------------------------------------------------------
  RTk.GPIO Random Output
  Randomly changes the output on the GPIO pins
--------------------------------------------------------------------------------
  Daniel Bull
  daniel@neonhorizon.co.uk
------------------------------------------------------------------------------*/


// Load Driver
require_once('PHP_GPIO/RTk.GPIO.php');
use PHP_GPIO\RTK\GPIO as GPIO;

// Open a connection to your RTk.GPIO
$GPIO = new GPIO();

// Set the pin numbering scheme we are going to use
$GPIO->setmode(GPIO::BCM);

// Set all pins to outputs
$GPIO->setup(GPIO::PINS, GPIO::OUT);

// Randomly change a pin output every 1000us
while(TRUE)
{
  $GPIO->output(rand(0, 27), rand(0, 1));
  usleep(1000);
}

// Cleanup
$GPIO->cleanup();
