#!/usr/bin/php
<?php
/*------------------------------------------------------------------------------
  RTk.GPIO Brutal Test
  Randomly changes the settings on the GPIO pins and reads/writes to them
--------------------------------------------------------------------------------
  Daniel Bull
  daniel@neonhorizon.co.uk
------------------------------------------------------------------------------*/


// Load Driver
require_once('PHP_GPIO/RTk.GPIO.php');
use PHP_GPIO\RTK\GPIO as GPIO;

// Open a connection to your RTk.GPIO
$GPIO = new GPIO();

// Set the pin numbering scheme we are going to use
$GPIO->setmode(GPIO::BCM);

// Randomly change a pin direction and read or write as fast as possible
$pull_up_down = array(GPIO::PUD_OFF, GPIO::PUD_DOWN, GPIO::PUD_UP);
while(TRUE)
{
  $random_pin = rand(0, 27);
  if(rand(0, 1))
  {
    // Read test
    $GPIO->setup($random_pin, GPIO::IN);
    $GPIO->input($random_pin);
  }
  else
  {
    // Write test
    $GPIO->setup($random_pin, GPIO::OUT, array('pull_up_down' => $pull_up_down[rand(0, 2)]));
    $GPIO->output($random_pin, rand(0, 1));
  }
}

// Cleanup
$GPIO->cleanup();
